package de.jmmo.data;

import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class BeanWithoutAppId implements Bean {
  
  @PropertyDefinition
  private String stringProperty = "";
  

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code BeanWithoutAppId}.
     * @return the meta-bean, not null
     */
    public static BeanWithoutAppId.Meta meta() {
        return BeanWithoutAppId.Meta.INSTANCE;
    }

    static {
        MetaBean.register(BeanWithoutAppId.Meta.INSTANCE);
    }

    @Override
    public BeanWithoutAppId.Meta metaBean() {
        return BeanWithoutAppId.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the stringProperty.
     * @return the value of the property
     */
    public String getStringProperty() {
        return stringProperty;
    }

    /**
     * Sets the stringProperty.
     * @param stringProperty  the new value of the property
     */
    public void setStringProperty(String stringProperty) {
        this.stringProperty = stringProperty;
    }

    /**
     * Gets the the {@code stringProperty} property.
     * @return the property, not null
     */
    public final Property<String> stringProperty() {
        return metaBean().stringProperty().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public BeanWithoutAppId clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            BeanWithoutAppId other = (BeanWithoutAppId) obj;
            return JodaBeanUtils.equal(getStringProperty(), other.getStringProperty());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getStringProperty());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("BeanWithoutAppId{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("stringProperty").append('=').append(JodaBeanUtils.toString(getStringProperty())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code BeanWithoutAppId}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code stringProperty} property.
         */
        private final MetaProperty<String> stringProperty = DirectMetaProperty.ofReadWrite(
                this, "stringProperty", BeanWithoutAppId.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "stringProperty");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    return stringProperty;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends BeanWithoutAppId> builder() {
            return new DirectBeanBuilder<>(new BeanWithoutAppId());
        }

        @Override
        public Class<? extends BeanWithoutAppId> beanType() {
            return BeanWithoutAppId.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code stringProperty} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> stringProperty() {
            return stringProperty;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    return ((BeanWithoutAppId) bean).getStringProperty();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    ((BeanWithoutAppId) bean).setStringProperty((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
