package org.saatsch.framework.jmmo.data.editor.fx.model;

import dev.morphia.annotations.*;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.saatsch.framework.jmmo.data.mongo.EditorObject;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@Entity("Base_Unit")
@Indexes(@Index(fields = {@Field(value = "appId")}, options = @IndexOptions(unique = true)))
public class UnitBase extends EditorObject {

  @PropertyDefinition
  private String someProperty;

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code UnitBase}.
     * @return the meta-bean, not null
     */
    public static UnitBase.Meta meta() {
        return UnitBase.Meta.INSTANCE;
    }

    static {
        MetaBean.register(UnitBase.Meta.INSTANCE);
    }

    @Override
    public UnitBase.Meta metaBean() {
        return UnitBase.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the someProperty.
     * @return the value of the property
     */
    public String getSomeProperty() {
        return someProperty;
    }

    /**
     * Sets the someProperty.
     * @param someProperty  the new value of the property
     */
    public void setSomeProperty(String someProperty) {
        this.someProperty = someProperty;
    }

    /**
     * Gets the the {@code someProperty} property.
     * @return the property, not null
     */
    public final Property<String> someProperty() {
        return metaBean().someProperty().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public UnitBase clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            UnitBase other = (UnitBase) obj;
            return JodaBeanUtils.equal(getSomeProperty(), other.getSomeProperty()) &&
                    super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = hash * 31 + JodaBeanUtils.hashCode(getSomeProperty());
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("UnitBase{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
        buf.append("someProperty").append('=').append(JodaBeanUtils.toString(getSomeProperty())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code UnitBase}.
     */
    public static class Meta extends EditorObject.Meta {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code someProperty} property.
         */
        private final MetaProperty<String> someProperty = DirectMetaProperty.ofReadWrite(
                this, "someProperty", UnitBase.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap(),
                "someProperty");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1323565801:  // someProperty
                    return someProperty;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends UnitBase> builder() {
            return new DirectBeanBuilder<>(new UnitBase());
        }

        @Override
        public Class<? extends UnitBase> beanType() {
            return UnitBase.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code someProperty} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> someProperty() {
            return someProperty;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1323565801:  // someProperty
                    return ((UnitBase) bean).getSomeProperty();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1323565801:  // someProperty
                    ((UnitBase) bean).setSomeProperty((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
