package org.saatsch.framework.jmmo.data;

import java.util.Map;

import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class DerivedBean extends ExampleNestedBean {

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code DerivedBean}.
     * @return the meta-bean, not null
     */
    public static DerivedBean.Meta meta() {
        return DerivedBean.Meta.INSTANCE;
    }

    static {
        MetaBean.register(DerivedBean.Meta.INSTANCE);
    }

    @Override
    public DerivedBean.Meta metaBean() {
        return DerivedBean.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    @Override
    public DerivedBean clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            return super.equals(obj);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash ^ super.hashCode();
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(32);
        buf.append("DerivedBean{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    @Override
    protected void toString(StringBuilder buf) {
        super.toString(buf);
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code DerivedBean}.
     */
    public static class Meta extends ExampleNestedBean.Meta {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, (DirectMetaPropertyMap) super.metaPropertyMap());

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        public BeanBuilder<? extends DerivedBean> builder() {
            return new DirectBeanBuilder<>(new DerivedBean());
        }

        @Override
        public Class<? extends DerivedBean> beanType() {
            return DerivedBean.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
    }

    //-------------------------- AUTOGENERATED END --------------------------
}
