package org.saatsch.framework.jmmo.data;

import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class ExampleNestedBean implements Bean {

  @PropertyDefinition
  private String arbitraryProperty = "";
  
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ExampleNestedBean}.
     * @return the meta-bean, not null
     */
    public static ExampleNestedBean.Meta meta() {
        return ExampleNestedBean.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ExampleNestedBean.Meta.INSTANCE);
    }

    @Override
    public ExampleNestedBean.Meta metaBean() {
        return ExampleNestedBean.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the arbitraryProperty.
     * @return the value of the property
     */
    public String getArbitraryProperty() {
        return arbitraryProperty;
    }

    /**
     * Sets the arbitraryProperty.
     * @param arbitraryProperty  the new value of the property
     */
    public void setArbitraryProperty(String arbitraryProperty) {
        this.arbitraryProperty = arbitraryProperty;
    }

    /**
     * Gets the the {@code arbitraryProperty} property.
     * @return the property, not null
     */
    public final Property<String> arbitraryProperty() {
        return metaBean().arbitraryProperty().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public ExampleNestedBean clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ExampleNestedBean other = (ExampleNestedBean) obj;
            return JodaBeanUtils.equal(getArbitraryProperty(), other.getArbitraryProperty());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getArbitraryProperty());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("ExampleNestedBean{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("arbitraryProperty").append('=').append(JodaBeanUtils.toString(getArbitraryProperty())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ExampleNestedBean}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code arbitraryProperty} property.
         */
        private final MetaProperty<String> arbitraryProperty = DirectMetaProperty.ofReadWrite(
                this, "arbitraryProperty", ExampleNestedBean.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "arbitraryProperty");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case -1642088985:  // arbitraryProperty
                    return arbitraryProperty;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends ExampleNestedBean> builder() {
            return new DirectBeanBuilder<>(new ExampleNestedBean());
        }

        @Override
        public Class<? extends ExampleNestedBean> beanType() {
            return ExampleNestedBean.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code arbitraryProperty} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> arbitraryProperty() {
            return arbitraryProperty;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1642088985:  // arbitraryProperty
                    return ((ExampleNestedBean) bean).getArbitraryProperty();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case -1642088985:  // arbitraryProperty
                    ((ExampleNestedBean) bean).setArbitraryProperty((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
