package de.osrg.base.beans.change;

import java.io.Serializable;
import java.util.Map;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.MetaBean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

@BeanDefinition
public class NestedBean implements Bean, Serializable {

  @PropertyDefinition
  private String stringPropertyInNestedBean;
  
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code NestedBean}.
     * @return the meta-bean, not null
     */
    public static NestedBean.Meta meta() {
        return NestedBean.Meta.INSTANCE;
    }

    static {
        MetaBean.register(NestedBean.Meta.INSTANCE);
    }

    /**
     * The serialization version id.
     */
    private static final long serialVersionUID = 1L;

    @Override
    public NestedBean.Meta metaBean() {
        return NestedBean.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the stringPropertyInNestedBean.
     * @return the value of the property
     */
    public String getStringPropertyInNestedBean() {
        return stringPropertyInNestedBean;
    }

    /**
     * Sets the stringPropertyInNestedBean.
     * @param stringPropertyInNestedBean  the new value of the property
     */
    public void setStringPropertyInNestedBean(String stringPropertyInNestedBean) {
        this.stringPropertyInNestedBean = stringPropertyInNestedBean;
    }

    /**
     * Gets the the {@code stringPropertyInNestedBean} property.
     * @return the property, not null
     */
    public final Property<String> stringPropertyInNestedBean() {
        return metaBean().stringPropertyInNestedBean().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public NestedBean clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            NestedBean other = (NestedBean) obj;
            return JodaBeanUtils.equal(getStringPropertyInNestedBean(), other.getStringPropertyInNestedBean());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getStringPropertyInNestedBean());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("NestedBean{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("stringPropertyInNestedBean").append('=').append(JodaBeanUtils.toString(getStringPropertyInNestedBean())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code NestedBean}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code stringPropertyInNestedBean} property.
         */
        private final MetaProperty<String> stringPropertyInNestedBean = DirectMetaProperty.ofReadWrite(
                this, "stringPropertyInNestedBean", NestedBean.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "stringPropertyInNestedBean");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1124274290:  // stringPropertyInNestedBean
                    return stringPropertyInNestedBean;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends NestedBean> builder() {
            return new DirectBeanBuilder<>(new NestedBean());
        }

        @Override
        public Class<? extends NestedBean> beanType() {
            return NestedBean.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code stringPropertyInNestedBean} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> stringPropertyInNestedBean() {
            return stringPropertyInNestedBean;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1124274290:  // stringPropertyInNestedBean
                    return ((NestedBean) bean).getStringPropertyInNestedBean();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1124274290:  // stringPropertyInNestedBean
                    ((NestedBean) bean).setStringPropertyInNestedBean((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
