package org.saatsch.framework.jmmo.basegame.common;

import java.io.Serializable;
import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

@BeanDefinition
public class LoginRequest implements Bean, Serializable {

  private static final long serialVersionUID = 4216245566842885760L;

  public LoginRequest() {

  }

  public LoginRequest(String user, String pass) {
    this.user = user;
    this.pass = pass;
  }

  @PropertyDefinition
  private String user;
  
  /**
   * the password. This is omitted from toString and equalsHashCode
   */
  @PropertyDefinition(equalsHashCodeStyle = "omit", toStringStyle= "omit")
  private String pass;


    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code LoginRequest}.
     * @return the meta-bean, not null
     */
    public static LoginRequest.Meta meta() {
        return LoginRequest.Meta.INSTANCE;
    }

    static {
        MetaBean.register(LoginRequest.Meta.INSTANCE);
    }

    @Override
    public LoginRequest.Meta metaBean() {
        return LoginRequest.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the user.
     * @return the value of the property
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the user.
     * @param user  the new value of the property
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Gets the the {@code user} property.
     * @return the property, not null
     */
    public final Property<String> user() {
        return metaBean().user().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the password. This is omitted from toString and equalsHashCode
     * @return the value of the property
     */
    public String getPass() {
        return pass;
    }

    /**
     * Sets the password. This is omitted from toString and equalsHashCode
     * @param pass  the new value of the property
     */
    public void setPass(String pass) {
        this.pass = pass;
    }

    /**
     * Gets the the {@code pass} property.
     * @return the property, not null
     */
    public final Property<String> pass() {
        return metaBean().pass().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public LoginRequest clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            LoginRequest other = (LoginRequest) obj;
            return JodaBeanUtils.equal(getUser(), other.getUser());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getUser());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("LoginRequest{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("user").append('=').append(JodaBeanUtils.toString(getUser())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code LoginRequest}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code user} property.
         */
        private final MetaProperty<String> user = DirectMetaProperty.ofReadWrite(
                this, "user", LoginRequest.class, String.class);
        /**
         * The meta-property for the {@code pass} property.
         */
        private final MetaProperty<String> pass = DirectMetaProperty.ofReadWrite(
                this, "pass", LoginRequest.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "user",
                "pass");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3599307:  // user
                    return user;
                case 3433489:  // pass
                    return pass;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends LoginRequest> builder() {
            return new DirectBeanBuilder<>(new LoginRequest());
        }

        @Override
        public Class<? extends LoginRequest> beanType() {
            return LoginRequest.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code user} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> user() {
            return user;
        }

        /**
         * The meta-property for the {@code pass} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> pass() {
            return pass;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3599307:  // user
                    return ((LoginRequest) bean).getUser();
                case 3433489:  // pass
                    return ((LoginRequest) bean).getPass();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3599307:  // user
                    ((LoginRequest) bean).setUser((String) newValue);
                    return;
                case 3433489:  // pass
                    ((LoginRequest) bean).setPass((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
