package org.saatsch.framework.jmmo.data.api;

import java.io.Serializable;
import java.util.Locale;
import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
public class LocalizedString implements Bean, Serializable {

  /**
   * the actual content of the String
   */
  @PropertyDefinition
  private String content = "";
  
  /**
   * the locale of the String
   */
  @PropertyDefinition
  private Locale locale;

  
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code LocalizedString}.
     * @return the meta-bean, not null
     */
    public static LocalizedString.Meta meta() {
        return LocalizedString.Meta.INSTANCE;
    }

    static {
        MetaBean.register(LocalizedString.Meta.INSTANCE);
    }

    /**
     * The serialization version id.
     */
    private static final long serialVersionUID = 1L;

    @Override
    public LocalizedString.Meta metaBean() {
        return LocalizedString.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the actual content of the String
     * @return the value of the property
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the actual content of the String
     * @param content  the new value of the property
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Gets the the {@code content} property.
     * @return the property, not null
     */
    public final Property<String> content() {
        return metaBean().content().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the locale of the String
     * @return the value of the property
     */
    public Locale getLocale() {
        return locale;
    }

    /**
     * Sets the locale of the String
     * @param locale  the new value of the property
     */
    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    /**
     * Gets the the {@code locale} property.
     * @return the property, not null
     */
    public final Property<Locale> locale() {
        return metaBean().locale().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public LocalizedString clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            LocalizedString other = (LocalizedString) obj;
            return JodaBeanUtils.equal(getContent(), other.getContent()) &&
                    JodaBeanUtils.equal(getLocale(), other.getLocale());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getContent());
        hash = hash * 31 + JodaBeanUtils.hashCode(getLocale());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("LocalizedString{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("content").append('=').append(JodaBeanUtils.toString(getContent())).append(',').append(' ');
        buf.append("locale").append('=').append(JodaBeanUtils.toString(getLocale())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code LocalizedString}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code content} property.
         */
        private final MetaProperty<String> content = DirectMetaProperty.ofReadWrite(
                this, "content", LocalizedString.class, String.class);
        /**
         * The meta-property for the {@code locale} property.
         */
        private final MetaProperty<Locale> locale = DirectMetaProperty.ofReadWrite(
                this, "locale", LocalizedString.class, Locale.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "content",
                "locale");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 951530617:  // content
                    return content;
                case -1097462182:  // locale
                    return locale;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends LocalizedString> builder() {
            return new DirectBeanBuilder<>(new LocalizedString());
        }

        @Override
        public Class<? extends LocalizedString> beanType() {
            return LocalizedString.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code content} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> content() {
            return content;
        }

        /**
         * The meta-property for the {@code locale} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Locale> locale() {
            return locale;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 951530617:  // content
                    return ((LocalizedString) bean).getContent();
                case -1097462182:  // locale
                    return ((LocalizedString) bean).getLocale();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 951530617:  // content
                    ((LocalizedString) bean).setContent((String) newValue);
                    return;
                case -1097462182:  // locale
                    ((LocalizedString) bean).setLocale((Locale) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
