package org.saatsch.framework.base.beans.change;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;
import org.joda.beans.MetaBean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;

@BeanDefinition
public class TopLevelBean implements Bean {

  @PropertyDefinition
  private String stringProperty;
  
  @PropertyDefinition
  private NestedBean nestedBean = new NestedBean();
  
  @PropertyDefinition
  private List<NestedBean> listOfNestedBeans = new ArrayList<>();
  
    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code TopLevelBean}.
     * @return the meta-bean, not null
     */
    public static TopLevelBean.Meta meta() {
        return TopLevelBean.Meta.INSTANCE;
    }

    static {
        MetaBean.register(TopLevelBean.Meta.INSTANCE);
    }

    @Override
    public TopLevelBean.Meta metaBean() {
        return TopLevelBean.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the stringProperty.
     * @return the value of the property
     */
    public String getStringProperty() {
        return stringProperty;
    }

    /**
     * Sets the stringProperty.
     * @param stringProperty  the new value of the property
     */
    public void setStringProperty(String stringProperty) {
        this.stringProperty = stringProperty;
    }

    /**
     * Gets the the {@code stringProperty} property.
     * @return the property, not null
     */
    public final Property<String> stringProperty() {
        return metaBean().stringProperty().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the nestedBean.
     * @return the value of the property
     */
    public NestedBean getNestedBean() {
        return nestedBean;
    }

    /**
     * Sets the nestedBean.
     * @param nestedBean  the new value of the property
     */
    public void setNestedBean(NestedBean nestedBean) {
        this.nestedBean = nestedBean;
    }

    /**
     * Gets the the {@code nestedBean} property.
     * @return the property, not null
     */
    public final Property<NestedBean> nestedBean() {
        return metaBean().nestedBean().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the listOfNestedBeans.
     * @return the value of the property
     */
    public List<NestedBean> getListOfNestedBeans() {
        return listOfNestedBeans;
    }

    /**
     * Sets the listOfNestedBeans.
     * @param listOfNestedBeans  the new value of the property
     */
    public void setListOfNestedBeans(List<NestedBean> listOfNestedBeans) {
        this.listOfNestedBeans = listOfNestedBeans;
    }

    /**
     * Gets the the {@code listOfNestedBeans} property.
     * @return the property, not null
     */
    public final Property<List<NestedBean>> listOfNestedBeans() {
        return metaBean().listOfNestedBeans().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public TopLevelBean clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            TopLevelBean other = (TopLevelBean) obj;
            return JodaBeanUtils.equal(getStringProperty(), other.getStringProperty()) &&
                    JodaBeanUtils.equal(getNestedBean(), other.getNestedBean()) &&
                    JodaBeanUtils.equal(getListOfNestedBeans(), other.getListOfNestedBeans());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getStringProperty());
        hash = hash * 31 + JodaBeanUtils.hashCode(getNestedBean());
        hash = hash * 31 + JodaBeanUtils.hashCode(getListOfNestedBeans());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(128);
        buf.append("TopLevelBean{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("stringProperty").append('=').append(JodaBeanUtils.toString(getStringProperty())).append(',').append(' ');
        buf.append("nestedBean").append('=').append(JodaBeanUtils.toString(getNestedBean())).append(',').append(' ');
        buf.append("listOfNestedBeans").append('=').append(JodaBeanUtils.toString(getListOfNestedBeans())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code TopLevelBean}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code stringProperty} property.
         */
        private final MetaProperty<String> stringProperty = DirectMetaProperty.ofReadWrite(
                this, "stringProperty", TopLevelBean.class, String.class);
        /**
         * The meta-property for the {@code nestedBean} property.
         */
        private final MetaProperty<NestedBean> nestedBean = DirectMetaProperty.ofReadWrite(
                this, "nestedBean", TopLevelBean.class, NestedBean.class);
        /**
         * The meta-property for the {@code listOfNestedBeans} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<NestedBean>> listOfNestedBeans = DirectMetaProperty.ofReadWrite(
                this, "listOfNestedBeans", TopLevelBean.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "stringProperty",
                "nestedBean",
                "listOfNestedBeans");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    return stringProperty;
                case -889023161:  // nestedBean
                    return nestedBean;
                case -427925065:  // listOfNestedBeans
                    return listOfNestedBeans;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends TopLevelBean> builder() {
            return new DirectBeanBuilder<>(new TopLevelBean());
        }

        @Override
        public Class<? extends TopLevelBean> beanType() {
            return TopLevelBean.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code stringProperty} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> stringProperty() {
            return stringProperty;
        }

        /**
         * The meta-property for the {@code nestedBean} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<NestedBean> nestedBean() {
            return nestedBean;
        }

        /**
         * The meta-property for the {@code listOfNestedBeans} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<NestedBean>> listOfNestedBeans() {
            return listOfNestedBeans;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    return ((TopLevelBean) bean).getStringProperty();
                case -889023161:  // nestedBean
                    return ((TopLevelBean) bean).getNestedBean();
                case -427925065:  // listOfNestedBeans
                    return ((TopLevelBean) bean).getListOfNestedBeans();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1890124038:  // stringProperty
                    ((TopLevelBean) bean).setStringProperty((String) newValue);
                    return;
                case -889023161:  // nestedBean
                    ((TopLevelBean) bean).setNestedBean((NestedBean) newValue);
                    return;
                case -427925065:  // listOfNestedBeans
                    ((TopLevelBean) bean).setListOfNestedBeans((List<NestedBean>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
